// Generated by gencpp from file fcu_core/uwb.msg
// DO NOT EDIT!


#ifndef FCU_CORE_MESSAGE_UWB_H
#define FCU_CORE_MESSAGE_UWB_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace fcu_core
{
template <class ContainerAllocator>
struct uwb_
{
  typedef uwb_<ContainerAllocator> Type;

  uwb_()
    : header()
    , tag1_id(0)
    , tag2_id(0)
    , distance(0.0)  {
    }
  uwb_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tag1_id(0)
    , tag2_id(0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _tag1_id_type;
  _tag1_id_type tag1_id;

   typedef int32_t _tag2_id_type;
  _tag2_id_type tag2_id;

   typedef float _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::fcu_core::uwb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fcu_core::uwb_<ContainerAllocator> const> ConstPtr;

}; // struct uwb_

typedef ::fcu_core::uwb_<std::allocator<void> > uwb;

typedef boost::shared_ptr< ::fcu_core::uwb > uwbPtr;
typedef boost::shared_ptr< ::fcu_core::uwb const> uwbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fcu_core::uwb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fcu_core::uwb_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fcu_core::uwb_<ContainerAllocator1> & lhs, const ::fcu_core::uwb_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.tag1_id == rhs.tag1_id &&
    lhs.tag2_id == rhs.tag2_id &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fcu_core::uwb_<ContainerAllocator1> & lhs, const ::fcu_core::uwb_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fcu_core

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fcu_core::uwb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fcu_core::uwb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fcu_core::uwb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fcu_core::uwb_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fcu_core::uwb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fcu_core::uwb_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fcu_core::uwb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8fe3100dfde9957ab6550e380f2e7809";
  }

  static const char* value(const ::fcu_core::uwb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8fe3100dfde9957aULL;
  static const uint64_t static_value2 = 0xb6550e380f2e7809ULL;
};

template<class ContainerAllocator>
struct DataType< ::fcu_core::uwb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fcu_core/uwb";
  }

  static const char* value(const ::fcu_core::uwb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fcu_core::uwb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"int32 tag1_id\n"
"int32 tag2_id\n"
"float32 distance\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::fcu_core::uwb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fcu_core::uwb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tag1_id);
      stream.next(m.tag2_id);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct uwb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fcu_core::uwb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fcu_core::uwb_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tag1_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tag1_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tag2_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tag2_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FCU_CORE_MESSAGE_UWB_H
